# Change these first
owner: adadaptedinc # Your GitHub username
repo: upptime-production # Your Github repository name

# Add your sites here
sites:
  - name: Ad Service API
    url: $SECRET_SITE_5
  - name: AdAdapted Direct
    url: https://direct.adadapted.com
  - name: AdAdapted Circulars
    url: https://circulars.adadapted.com
  - name: AdAdapted Direct Reporting API
    url: $SECRET_SITE_1
  - name: AdAdapted Direct Service API
    url: $SECRET_SITE_2
  - name: Circular API
    url: $SECRET_SITE_3
  - name: Telemetry API
    url: $SECRET_SITE_4

notifications:
  - type: slack
    channel: $SLACK_CHANNEL
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.adadapted.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://secureservercdn.net/45.40.148.147/cnp.503.myftpupload.com/wp-content/uploads/2020/05/cropped-AdAdapted-Logo.png
  name: AdAdapted
  introTitle: "AdAdapted Production Status"
  introMessage: This status page provides realtime status updates for AdAdapted API's and services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration